spring.application.name=parle-moi-backend

# Base de donnees
spring.datasource.url=jdbc:postgresql://localhost:5432/parlemoi
spring.datasource.username=parlemoi_user
spring.datasource.password=parlemoi_dev_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Port du serveur
server.port=8080

